var value = +prompt("Enter a value : ");
document.write("Result : <br>The value is : " + value + "<br>.................<br>");
document.write("The value of ++value is : " + (++value));
document.write("<br>The value after ++value is : " + value + "<br>.................<br>");
document.write("The value of value++ is : " + (value++));
document.write("<br>The value after value++ is : " + value + "<br>.................<br>");
document.write("The value of --value is : "+(--value));
document.write("<br>The value after --value is : "+value+"<br>.................<br>");
document.write("The value of value-- is : "+(value--));
document.write("<br>The value after value-- is : "+value+"<br>.................<br>");